# schema_fixer.py
import json
from datetime import datetime

class LocalBusinessSchemaGenerator:
    def __init__(self, business_data):
        self.name = business_data['name']
        self.address = business_data['address']
        self.phone = business_data['phone']
        self.url = business_data['url']
        self.service_type = business_data['service_type']  # plumber, roofer, etc.
        self.hours = business_data.get('hours', {})
    
    def generate_schema(self):
        """Generate complete LocalBusiness JSON-LD"""
        
        # Map service types to Schema.org types
        schema_types = {
            'plumber': 'Plumber',
            'roofer': 'RoofingContractor',
            'electrician': 'Electrician',
            'hvac': 'HVACBusiness',
            'general': 'LocalBusiness'
        }
        
        business_type = schema_types.get(self.service_type, 'LocalBusiness')
        
        schema = {
            "@context": "https://schema.org",
            "@type": business_type,
            "name": self.name,
            "address": {
                "@type": "PostalAddress",
                "streetAddress": self.address['street'],
                "addressLocality": self.address['city'],
                "addressRegion": self.address['state'],
                "postalCode": self.address['zip'],
                "addressCountry": "US"
            },
            "telephone": self.phone,
            "url": self.url,
            "priceRange": "$$"
        }
        
        # Add hours if provided
        if self.hours:
            schema["openingHoursSpecification"] = self._format_hours()
        
        return json.dumps(schema, indent=2)
    
    def _format_hours(self):
        """Format opening hours for schema"""
        hours_spec = []
        day_map = {
            'monday': 'Mo', 'tuesday': 'Tu', 'wednesday': 'We',
            'thursday': 'Th', 'friday': 'Fr', 'saturday': 'Sa', 'sunday': 'Su'
        }
        
        for day, hours in self.hours.items():
            if hours.get('open') and hours.get('close'):
                hours_spec.append({
                    "@type": "OpeningHoursSpecification",
                    "dayOfWeek": day_map.get(day.lower(), day),
                    "opens": hours['open'],
                    "closes": hours['close']
                })
        
        return hours_spec
    
    def generate_html(self):
        """Generate HTML with embedded schema"""
        schema_json = self.generate_schema()
        return f'''<!-- LocalBusiness Schema generated by AgentAir -->
<script type="application/ld+json">
{schema_json}
</script>'''
